// react/src/Grid.js
import React from 'react';
import Square from './Square';
import styled from 'styled-components';

const GridContainer = styled.div`
    display: flex;
    flex-direction: column; /* Stack rows vertically */
    align-items: center; /* Center the grid items */
`;

const RowContainer = styled.div`
    display: flex; /* Arrange squares in a row */
`;

function Grid({ grid, onSquareClick }) {
    return (
        <GridContainer>
            {grid.map((row, rowIndex) => (
                <RowContainer key={rowIndex}>
                    {row.map((cell, colIndex) => (
                        <Square
                            key={`${rowIndex}-${colIndex}`}
                            color={cell ? cell.color || cell : null}
                            onClick={() => onSquareClick(rowIndex, colIndex)}
                            willDisappear={cell ? cell.willDisappear : false}
                            bottomRow={rowIndex === grid.length - 1}
                        />
                    ))}
                </RowContainer>
            ))}
        </GridContainer>
    );
}

export default Grid;

// vue/src/components/Grid.vue
<template>
    <div class="grid">
        <div class="row" v-for="(row, rowIndex) in grid" :key="rowIndex">
            <Cell v-for="(cell, colIndex) in row" :key="colIndex" :color="cell"
                :bottomRow="rowIndex === grid.length - 1" :willDisappear="false"
                @click="$emit('cell-click', rowIndex, colIndex)" />
        </div>
    </div>
</template>

<script>
import Cell from "./Cell.vue"; // adjust the path as needed

export default {
    name: "GridComponent",
    props: {
        grid: {
            type: Array,
            default: () => []
        }
    },
    components: {
        Cell
    }
};
</script>

<style scoped>
.grid {
    display: flex;
    flex-direction: column;
}

.row {
    display: flex;
}
</style>
