// angular/src/app/grid.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CellComponent } from './cell.component';

@Component({
  selector: 'app-grid',
  standalone: true,
  imports: [CommonModule, CellComponent],
  templateUrl: './grid.component.html',
  styleUrls: ['./grid.component.css']
})
export class GridComponent {
  @Input() grid: (string | null)[][] = [];
  @Output() cellClick = new EventEmitter<{ row: number; col: number }>();

  onCellClick(row: number, col: number): void {
    this.cellClick.emit({ row, col });
  }
}

<div class="grid">
  <div class="row" *ngFor="let row of grid; let rowIndex = index">
    <app-cell
      *ngFor="let cell of row; let colIndex = index"
      [color]="cell"
      [bottomRow]="rowIndex === grid.length - 1"
      [willDisappear]="false"
      [row]="rowIndex"
      [col]="colIndex"
      (cellClick)="onCellClick(rowIndex, colIndex)">
    </app-cell>
  </div>
</div>

// vue/src/components/Grid.vue
<template>
    <div class="grid">
        <div class="row" v-for="(row, rowIndex) in grid" :key="rowIndex">
            <Cell v-for="(cell, colIndex) in row" :key="colIndex" :color="cell"
                :bottomRow="rowIndex === grid.length - 1" :willDisappear="false"
                @click="$emit('cell-click', rowIndex, colIndex)" />
        </div>
    </div>
</template>

<script>
import Cell from "./Cell.vue"; // adjust the path as needed

export default {
    name: "GridComponent",
    props: {
        grid: {
            type: Array,
            default: () => []
        }
    },
    components: {
        Cell
    }
};
</script>

<style scoped>
.grid {
    display: flex;
    flex-direction: column;
}

.row {
    display: flex;
}
</style>
